version: "3.9"

services:
  agario:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agario_blazor
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped
